# Generated by Django 4.2.6 on 2023-11-02 01:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mensagem', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('imagem', models.FileField(upload_to='portifolio/projetos', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg'])])),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.projetos')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.tags')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosFuncionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.funcionalidades')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.projetos')),
            ],
        ),
    ]
