# Generated by Django 4.2.6 on 2023-10-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_alter_projetos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetosFuncionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portifolio.projetos')),
            ],
        ),
    ]
